version: "3.2"
services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Db@Version"
      ACCEPT_EULA: "Y"